### ISSUE TITLE
Support for union/intersection types?

### ISSUE THREAD

**Issue by jpirnat** [moddengine/Dice#3]
Dice fails to instantiate classes which use union or intersection types. A quick demo:

```PHP
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

$dice = new \Dice\Dice();

$rule = [
	'constructParams' => [
		'one',
		'two',
		'three',
		'four',
		'five',
		'six',
		'seven',
		'eight',
		'nine',
		'ten',
	]
];
$dice = $dice->addRule(Foo::class, $rule);

class Foo
{
	public function __construct(
		string $one,
		string|int $two,
		string|int $three,
		string|int $four,
		string $five,
		string $six,
		string $seven,
		string $eight,
		string $nine,
		string $ten
	) {
		print_r([$one, $two, $three, $four, $five, $six, $seven, $eight, $nine, $ten]);
	}
}

$foo = $dice->create(Foo::class);
```

Output:
```
Fatal error: Uncaught Error: Call to undefined method ReflectionUnionType::isBuiltin() in dicetest/vendor/moddengine/dice/src/Dice.php:370
Stack trace:
#0 dicetest/vendor/moddengine/dice/src/Dice.php(170): Dice\Dice->getParams(Object(ReflectionMethod), Array)
#1 dicetest/vendor/moddengine/dice/src/Dice.php(136): Dice\Dice->getClosure('Foo', Array)
#2 dicetest/index.php(42): Dice\Dice->create('Foo')
#3 {main}
  thrown in dicetest/vendor/moddengine/dice/src/Dice.php on line 370
```

I wouldn't have thought this would be worth asking for, but some popular libraries are apparently already using union types out in the wild (e.g. Symfony HttpFoundation).

(I've also filed this issue with the base project level-2/dice, but this fork seems more regularly maintained.)

**Comment by cseufert** [comment]
I have merged support for scalar types based on this patch https://github.com/Level-2/Dice/pull/204 from @thisispiers

https://github.com/moddengine/Dice/releases/tag/v4.1.5
